### ISSUE TITLE
On linux, parts of the tetris grid are cut off

### ISSUE THREAD

**Issue by panmari** [simplay/bofrev#27]
To the right, the grid is cut off by unnaturally. Could it be, that the window decorations interfere with the window width?
![game_051](https://cloud.githubusercontent.com/assets/719020/9692957/f29dcc1c-534c-11e5-87e9-43f2bc5d5884.png)

**Comment by simplay** [comment]
Commit 90d4d14 should fixes this issue on windows and linux (at least for me; have tested it on my windows7 and ubuntu10.04 systems).

@panmari: can you confirm that this issue has been fixed?

**Comment by panmari** [comment]
Does not occur anymore on my system. Thanks :+1:
