### ISSUE TITLE
Clean up aftersuccess actions

### ISSUE THREAD

**Issue by panmari** [simplay/bofrev#44]
[This line](https://github.com/simplay/bofrev/blob/master/.travis.yml#L10) currently does nothing else than printing the help page of coveralls, as visible in the travis log:

```
$ coveralls
Using Ext extension for JSON.
Commands:
  coveralls help [COMMAND]  # Describe available commands or one specific com...
  coveralls last            # View the last build for this repository on Cove...
  coveralls open            # View this repository on Coveralls.
  coveralls push            # Runs your test suite and pushes the coverage re...
  coveralls report          # Runs your test suite locally and displays cover...
  coveralls service         # View this repository on your CI service's website.
  coveralls version         # See version
```

Is this intended?

**Comment by simplay** [comment]
@panmari: I removed this covaralls aftersuccess call. It was an obstacle of some _try and error I don't know how to make it run, finally found a solution but forgot to clean the travis yaml file up_ actions... XD
